{
    "name": "Forecast",
    "channels": ["conda-forge"],
    "dependencies": [
        "python=3.7", "prophet",
        {
            "pip": [
                "pystan",
                "mlflow",
                "jupyterlab",
                "plotly",
                "seaborn",
                "statsmodels",
                "scikit-learn",
                "ipywidgets"
            ],
        },
    ],
}