{"name": "Forecast",
                "channels": ["conda-forge"],
                "dependencies": [ "python=3.7",
                    {"pip": [
                            "pystan",
                            "mlflow",
                            "plotly",
                            "seaborn",
                            "statsmodels",
                            "scikit-learn",
                            "ipywidgets",
                            "prophet"
                        ],
                    },
                ],
            }